package com.promptwhisperer.services

import com.promptwhisperer.models.BehaviourProfile
import com.promptwhisperer.models.Guardrail
import com.promptwhisperer.models.PromptDepth
import com.promptwhisperer.models.PromptSessionConfig

/**
 * Modular prompt builder.
 *
 * Composes a final prompt from independent, reusable blocks:
 * - Core Implementation Block
 * - Behaviour Profile Block
 * - Security Block
 * - Architecture Block
 * - Operational Block
 * - Documentation Block
 * - Testing Block
 * - Guardrail Block
 * - Depth-specific details
 *
 * This avoids giant template strings and allows dynamic composition.
 */
interface PromptBuilder {
    fun buildImplementationPrompt(task: String, config: PromptSessionConfig): String
}

class PromptBuilderImpl : PromptBuilder {
    override fun buildImplementationPrompt(task: String, config: PromptSessionConfig): String {
        val blocks = mutableListOf<String>()

        blocks.add(buildHeader(task))
        blocks.add(buildGoalSection(task))
        blocks.add(buildBehaviourProfileSection(config.behaviourProfile))
        blocks.add(buildImplementationPlanSection(config.promptDepth))
        blocks.add(buildArchitectureSection(config.promptDepth))
        blocks.add(buildSecuritySection(config.enabledGuardrails))
        blocks.add(buildCodeQualitySection(config.enabledGuardrails, config.promptDepth))
        blocks.add(buildOperationalSection(config.enabledGuardrails, config.promptDepth))
        blocks.add(buildDocumentationSection(config.enabledGuardrails, config.promptDepth))
        blocks.add(buildTestingSection(config.enabledGuardrails, config.promptDepth))
        blocks.add(buildConstraintsSection(config.enabledGuardrails, config.behaviourProfile))
        blocks.add(buildOutputExpectationsSection(config.promptDepth))

        return blocks.filter { it.isNotEmpty() }.joinToString("\n\n")
    }

    private fun buildHeader(task: String): String = """
        # Copilot Implementation Prompt
        
        Generated by Prompt Whisperer — design better implementation instructions for AI coding assistants.
    """.trimIndent()

    private fun buildGoalSection(task: String): String = """
        ## Goal
        
        $task
    """.trimIndent()

    private fun buildBehaviourProfileSection(profile: BehaviourProfile): String = """
        ## Engineering Philosophy
        
        This request uses the **${profile.displayName}** profile.
        
        Philosophy: *${profile.philosophy}*
        
        Focus areas: ${profile.priorityAreas.joinToString(", ")}
    """.trimIndent()

    private fun buildImplementationPlanSection(depth: PromptDepth): String {
        val baseSteps = """
        ## Implementation Plan
        
        Before you start coding:
        1. Analyse the existing project structure and identify relevant files.
        2. Break down the requested feature into clear, testable sub-tasks.
        3. Identify dependencies and potential conflicts.
        4. Propose the implementation approach (smallest working version first).
        5. Verify the plan aligns with the requirements above.
        """.trimIndent()

        return if (depth.detailMultiplier > 1.0f) {
            baseSteps + """
            
            Then, during implementation:
            6. Implement one sub-task at a time.
            7. Verify each step with targeted tests.
            8. Refactor incrementally — do not wait for the end.
            9. Document as you go, not after.
            10. Confirm the final result meets acceptance criteria.
            """.trimIndent()
        } else {
            baseSteps
        }
    }

    private fun buildArchitectureSection(depth: PromptDepth): String {
        if (depth == PromptDepth.MINIMAL) {
            return ""
        }

        return """
        ## Architectural Considerations
        
        - Preserve existing code organisation and naming conventions.
        - Do not break public APIs or introduce hard-to-reverse changes unless explicitly requested.
        - Identify any new abstractions clearly by name and responsibility.
        - If you need a new module, explain why and what it encapsulates.
        ${if (depth.detailMultiplier >= 1.5f) {
            "- Propose any infrastructure or dependencies needed.\n- Diagram the high-level flow if the change affects multiple modules."
        } else {
            ""
        }}
        """.trimIndent()
    }

    private fun buildSecuritySection(guardrails: List<Guardrail>): String {
        val securityGuardrails = guardrails.filter { it.category.name == "SECURITY" }
        if (securityGuardrails.isEmpty()) {
            return ""
        }

        val items = securityGuardrails.map { "- ${it.name}: ${it.description}" }.joinToString("\n")
        return """
        ## Security Requirements
        
        $items
        """.trimIndent()
    }

    private fun buildCodeQualitySection(guardrails: List<Guardrail>, depth: PromptDepth): String {
        val qualityGuardrails = guardrails.filter { it.category.name == "CODE_QUALITY" }

        val base = if (qualityGuardrails.isNotEmpty()) {
            val items = qualityGuardrails.map { "- ${it.name}: ${it.description}" }.joinToString("\n")
            """## Code Quality
            
            $items"""
        } else {
            """## Code Quality
            
            - Keep implementation simple and maintainable.
            - Follow existing project conventions for naming, structure, and patterns.
            - Add inline comments for non-obvious logic."""
        }

        return if (depth.detailMultiplier > 1.0f) {
            base + """
            
            - Make functions focused on a single responsibility.
            - Use meaningful variable and function names.
            - Keep files reasonably sized; split if > 300 lines.
            """.trimIndent()
        } else {
            base
        }
    }

    private fun buildOperationalSection(guardrails: List<Guardrail>, depth: PromptDepth): String {
        val opGuardrails = guardrails.filter { it.category.name == "OPERATIONAL" }

        if (opGuardrails.isEmpty() && depth == PromptDepth.MINIMAL) {
            return ""
        }

        val base = if (opGuardrails.isNotEmpty()) {
            val items = opGuardrails.map { "- ${it.name}: ${it.description}" }.joinToString("\n")
            """## Operational Considerations
            
            $items"""
        } else {
            """## Operational Considerations
            
            - Preserve backwards compatibility unless breaking changes are explicitly required.
            - Minimise the blast radius — limit what can go wrong."""
        }

        return if (depth.detailMultiplier >= 1.5f) {
            base + """
            
            - Plan a rollback strategy (how to undo this change quickly if needed).
            - Identify any migration steps if data formats change.
            - Consider staged rollout if the change is large.
            """.trimIndent()
        } else {
            base
        }
    }

    private fun buildDocumentationSection(guardrails: List<Guardrail>, depth: PromptDepth): String {
        val hasDocGuardrail = guardrails.any { it.id == "cq_require_docs" }

        return if (hasDocGuardrail) {
            """## Documentation Requirements
            
            - Update README if this changes user-facing behaviour.
            - Update API documentation if public interfaces change.
            ${if (depth.detailMultiplier >= 1.5f) {
                "- Add architectural notes if the design is not obvious.\n- Include examples or usage patterns if applicable."
            } else {
                ""
            }}
            """.trimIndent()
        } else if (depth.detailMultiplier > 1.0f) {
            """## Documentation
            
            - Update relevant documentation (README, inline comments, API docs).
            """.trimIndent()
        } else {
            ""
        }
    }

    private fun buildTestingSection(guardrails: List<Guardrail>, depth: PromptDepth): String {
        val testGuardrail = guardrails.find { it.id == "cq_require_tests" }

        return if (testGuardrail != null) {
            """## Testing Requirements
            
            - Add tests matching the existing framework and style in this project.
            - Cover happy path, edge cases, and any known regression scenarios.
            - Run: [command for new tests], then [command for full test suite].
            ${if (depth.detailMultiplier >= 1.5f) {
                "- Aim for > 80% code coverage on new/modified functions.\n- Include integration tests if the change affects multiple modules."
            } else {
                ""
            }}
            """.trimIndent()
        } else if (depth.detailMultiplier > 1.0f) {
            """## Testing
            
            - Add tests if the project has a test framework.
            - Or explain why tests are not needed.
            """.trimIndent()
        } else {
            ""
        }
    }

    private fun buildConstraintsSection(guardrails: List<Guardrail>, profile: BehaviourProfile): String {
        val constraints = mutableListOf<String>()

        constraints.add("Do not modify files unrelated to this feature.")
        constraints.add("Do not add telemetry, tracking, or analytics without explicit comment.")

        if (guardrails.any { it.id == "sec_no_network" }) {
            constraints.add("No hidden external API calls or network requests.")
        }
        if (guardrails.any { it.id == "sec_no_secrets" }) {
            constraints.add("No hardcoded secrets, API keys, or credentials.")
        }
        if (guardrails.any { it.id == "arch_minimize_deps" }) {
            constraints.add("Do not add new dependencies unless absolutely necessary. Justify any new dependency.")
        }
        if (guardrails.any { it.id == "arch_avoid_rewrites" }) {
            constraints.add("Prefer incremental changes over broad architectural rewrites.")
        }

        return """
        ## Constraints
        
        ${constraints.map { "- $it" }.joinToString("\n")}
        """.trimIndent()
    }

    private fun buildOutputExpectationsSection(depth: PromptDepth): String {
        return """
        ## Output Expected From You
        
        ${if (depth == PromptDepth.MINIMAL) {
            """- Code changes with brief explanations.
            - List of files created or modified.
            - How to verify it works (1-2 test commands)."""
        } else if (depth == PromptDepth.STANDARD) {
            """- Brief explanation of your approach.
            - List of files to create or modify.
            - Code changes with inline comments where logic is non-obvious.
            - Test or verification commands so I can confirm it works.
            - Any assumptions you made."""
        } else if (depth == PromptDepth.DETAILED) {
            """- Detailed explanation of your approach and why you chose it.
            - List of files to create or modify, with the reason for each.
            - Code changes with comprehensive inline comments.
            - Unit/integration test code.
            - Updated documentation with examples.
            - Verification commands (individual and full suite).
            - Any trade-offs or alternatives you considered.
            - Risk assessment and mitigation."""
        } else { // ENTERPRISE
            """- Executive summary of the change and its impact.
            - Detailed architecture explanation and design rationale.
            - List of all affected files and modules.
            - Full code with architecture-level comments.
            - Comprehensive test suite with coverage metrics.
            - Updated documentation (README, API docs, architectural notes).
            - Migration/rollback plan.
            - Performance and scalability analysis.
            - Security audit and compliance notes.
            - Verification commands (unit, integration, E2E, performance).
            - Trade-off analysis and alternative approaches."""
        }}
        """.trimIndent()
    }
}

